eureka:
  client:
    service-url:
      default-zone: https://${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
spring:
  boot:
    admin:
      client:
        url: http://localhost:3333
  cloud:
    config:
      override-system-properties: false

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
redis:
  host: 127.0.0.1
  port: 6379