spring:
  config:
    customer-url: http://127.0.0.1:9191/api/v1/customer/
    product-url: http://127.0.0.1:9090/api/v1/product/
    payment-url: http://127.0.0.1:9494/api/v1/payment/
  datasource:
    url: jdbc:postgresql://localhost:5433/order
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}