spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/product
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}